apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-core-object-counts
spec:
  hard:
    configmaps: "100" 
    persistentvolumeclaims: "4" 
    replicationcontrollers: "20" 
    secrets: "100" 
    services: "100" 
